# Generated by Django 4.1.7 on 2023-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="tier",
            name="thumbnail_sizes",
        ),
        migrations.AddField(
            model_name="tier",
            name="thumbnail_sizes",
            field=models.ManyToManyField(to="user.size"),
        ),
    ]
